name: Workflow Commands
on: [push]

jobs:
    testing-wf-commands:
        runs-on: ubuntu-latest
        steps:
            - name: Setting an error message
              run: echo "::error::Missing semicolon"
            - name: Setting an error message with parameters
              run: echo "::error file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing semicolon"
            - name: Setting a debug message with parameters
              run: echo "::debug file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing semicolon"
            - name: Setting a warning message with parameters
              run: echo "::warning file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing semicolon"
            - name: Setting a notice message with parameters
              run: echo "::notice file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing semicolon"
            - name: Group of logs
              run: |
                echo "::group::My group title"
                echo "Inside group 1"
                echo "Inside group 2"
                echo "::endgroup::"
                echo "Outside group"
            - name: Masking a value
              run: echo "::add-mask::Secret String"
            - name: Echo a secret
              run: echo "Secret String"